config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  resources :books do
    member do
      get 'history'
    end
  end

  resources :borrows, only: [:create, :destroy]

  # Other routes...

  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  get '/dashboard', to: 'users#dashboard', as: 'dashboard'

  get '/register', to: 'users#new', as: 'register'
  post '/users', to: 'users#create'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :borrows, dependent: :destroy
  has_many :users, through: :borrows
  validates :title, :author, :publish_year, presence: true

  def available?
    current_borrow.nil?
  end

  def current_borrow
    borrows.find_by(ended_at: nil)
  end

  def self.search(query)
    where("title LIKE ? OR author LIKE ?", "%#{query}%", "%#{query}%")
  end
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, :book_id, :started_at, presence: true
  validate :book_must_be_available, on: :create

  def book_must_be_available
    errors.add(:book, "is already borrowed") unless book.available?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :borrows, dependent: :destroy
  has_many :borrowed_books, through: :borrows, source: :book

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true, format: { with: /\A\d{10}\z/, message: "must be 10 digits" }
  validates :date_of_birth, presence: true
  validates :membership_type, presence: true
  # validates :membership_expiry_date, presence: true
  validates :role, presence: true

  before_validation :set_default_role

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def set_default_role
    self.role ||= 'member'
    self.membership_type ||= 'standard'
    self.membership_expiry_date ||= Date.today.next_year
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path # Assuming you have a route for login
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :history]
  before_action :require_login, only: [:show, :edit, :update, :destroy, :history]

  def index
    @books = if params[:query].present?
               Book.search(params[:query]).paginate(page: params[:page], per_page: 10)
             else
               Book.paginate(page: params[:page], per_page: 10)
             end
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  def history
    @borrows = @book.borrows.includes(:user).order(started_at: :desc)
  end

  private

  def set_book
    @book = Book.find(params[:id])
    Rails.logger.debug "Book found: #{@book.inspect}"
  end


  def book_params
    params.require(:book).permit(:title, :author, :publish_year)
  end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :require_login
  before_action :set_borrow, only: [:destroy]
  before_action :authorize_user, only: [:destroy]

  def create
    @borrow = current_user.borrows.build(borrow_params)
    @borrow.started_at = Time.current
    if @borrow.save
      redirect_to dashboard_path, notice: 'Book borrowed successfully.'
    else
      redirect_to books_path, alert: 'Unable to borrow book.'
    end
  end

  def destroy
    if @borrow.update(ended_at: Time.current)
      redirect_to dashboard_path, notice: 'Book returned successfully.'
    else
      redirect_to dashboard_path, alert: 'Unable to return book.'
    end
  end

  private

  def set_borrow
    @borrow = Borrow.find(params[:id])
  end

  def authorize_user
    unless @borrow.user == current_user
      redirect_to dashboard_path, alert: 'You are not authorized to return this book.'
    end
  end

  def borrow_params
    params.permit(:book_id)
  end

  def require_login
    unless logged_in?
      redirect_to login_path, alert: 'You must be logged in to borrow a book.'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Email or password is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:dashboard, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.joined_date = Date.today # Set the joined date to today
    @user.role = 'member' # Set the default role to 'member'
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Account created successfully.'
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Account deleted successfully.'
  end

  # def dashboard
  #   @borrows = current_user.borrows.includes(:book)
  # end

  def dashboard
    @borrows = current_user.borrows.includes(:book)
    case params[:filter]
    when 'not_returned'
      @borrows = @borrows.where(ended_at: nil)
    when 'returned'
      @borrows = @borrows.where.not(ended_at: nil)
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :address, :phone, :date_of_birth, :membership_type, :profile_picture)
  end

  def require_login
    unless logged_in?
      redirect_to login_path, alert: 'You must be logged in to access this section.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/sessions_helper.rb
# app/helpers/sessions_helper.rb
module SessionsHelper
  # Define any methods you need here
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Publish year:</strong>
    <%= book.publish_year %>
  </p>

</div>

app/views/books/_book_card.html.erb
<!-- app/views/books/_book_card.html.erb -->
<div class="w-full p-4">
  <%= link_to book_path(book), class: "block bg-white shadow-md hover:shadow-xl rounded-lg overflow-hidden" do %>
    <div class="relative pb-48 overflow-hidden">
      <!-- Utilisation du titre du livre pour générer une URL unique pour chaque livre -->
      <img class="absolute inset-0 h-full w-full object-cover" src="https://source.unsplash.com/featured/?<%= ERB::Util.url_encode(book.title) %>" alt="<%= book.title %>">
    </div>
    <div class="p-4">
      <span class="inline-block px-2 py-1 leading-none bg-orange-200 text-orange-800 rounded-full font-semibold uppercase tracking-wide text-xs">New</span>
      <h2 class="mt-2 mb-2 font-bold"><%= book.title %></h2>
      <p class="text-sm"><%= book.author %></p>
      <div class="mt-3 flex items-center">
        <span class="text-sm font-semibold">Published Year:</span>&nbsp;<span class="font-bold text-xl"><%= book.publish_year %></span>
      </div>
    </div>
    <div class="p-4 border-t border-b text-xs text-gray-700">
      <span class="flex items-center mb-1">
        <i class="far fa-clock fa-fw mr-2 text-gray-900"></i> <%= book.available? ? "Available" : "Not Available" %>
      </span>
      <% if !book.available? %>
        <span class="flex items-center">
          <i class="far fa-user fa-fw mr-2 text-gray-900"></i> Borrowed by <%= book.current_borrow.user.full_name %>
        </span>
        <span class="flex items-center">
          <i class="far fa-calendar fa-fw mr-2 text-gray-900"></i> Due Date: <%= book.current_borrow.ended_at || "Not specified" %>
        </span>
      <% end %>
    </div>
  <% end %>
  <% if !book.available? && book.current_borrow.user == current_user %>
    <div class="p-4 text-sm text-gray-600">
      <%= button_to 'Return Book', borrow_path(book.current_borrow), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded ml-2" %>
    </div>
  <% end %>
</div>

app/views/books/_form.html.erb
<!-- app/views/books/_form.html.erb -->
<%= form_with model: book, local: true do |form| %>
  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div class="mb-4">
    <%= form.label :author, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :author, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div class="mb-4">
    <%= form.label :publish_year, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.number_field :publish_year, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>
  <div class="flex items-center justify-between">
    <%= form.submit 'Save', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1 class="text-5xl font-bold mb-10">Edit Book</h1>
<div class="max-w-2xl mx-auto">
  <%= render 'form', book: @book %>
</div>

app/views/books/history.html.erb
<!-- app/views/books/history.html.erb -->

<h1 class="text-3xl font-bold mb-4">Borrow History for <%= @book.title %></h1>

<table class="min-w-full bg-white">
  <thead>
  <tr>
    <th class="py-2 px-4 border-b-2 border-gray-200 bg-gray-100 text-left text-sm font-semibold text-gray-600 uppercase">Borrower</th>
    <th class="py-2 px-4 border-b-2 border-gray-200 bg-gray-100 text-left text-sm font-semibold text-gray-600 uppercase">Start Date</th>
    <th class="py-2 px-4 border-b-2 border-gray-200 bg-gray-100 text-left text-sm font-semibold text-gray-600 uppercase">End Date</th>
  </tr>
  </thead>
  <tbody>
  <% @borrows.each do |borrow| %>
    <tr>
      <td class="py-2 px-4 border-b border-gray-200"><%= borrow.user.full_name %></td>
      <td class="py-2 px-4 border-b border-gray-200"><%= borrow.started_at.strftime("%B %d, %Y") %></td>
      <td class="py-2 px-4 border-b border-gray-200"><%= borrow.ended_at ? borrow.ended_at.strftime("%B %d, %Y") : "Currently borrowed" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/index.html.erb
<!-- app/views/books/index.html.erb -->
<h1 class="text-3xl font-bold mb-4">Books</h1>

<%= form_with url: books_path, method: :get, local: true, class: "mb-4" do |form| %>
  <div class="flex">
    <%= form.text_field :query, placeholder: "Search by title, author, or keyword", class: "w-full p-2 rounded-l border border-gray-300" %>
    <%= form.submit "Search", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r" %>
  </div>
<% end %>

<%= link_to 'Add New Book', new_book_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4 inline-block" %>

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
  <% @books.each do |book| %>
    <div class="block book-card">
      <%= link_to book_path(book) do %>
        <%= render partial: 'books/book_card', locals: { book: book } %>
      <% end %>
    </div>
  <% end %>
</div>

<div class="mt-6">
  <%= will_paginate @books %>
</div>

app/views/books/new.html.erb
<h1 class="text-5xl font-bold mb-10">Add New Book</h1>
<div class="max-w-2xl mx-auto">
  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<!-- app/views/books/show.html.erb -->
<div class="max-w-2xl mx-auto p-4">
  <div class="c-card block bg-white shadow-md hover:shadow-xl rounded-lg overflow-hidden">
    <div class="relative pb-48 overflow-hidden">
      <img class="absolute inset-0 h-full w-full object-cover" src="https://source.unsplash.com/random/300x300" alt="<%= @book.title %>">
    </div>
    <div class="p-4">
      <h2 class="mt-2 mb-2 font-bold text-2xl"><%= @book.title %></h2>
      <p class="text-lg"><%= @book.author %></p>
      <div class="mt-3 flex items-center">
        <span class="text-lg font-semibold">Published Year:</span>&nbsp;<span class="font-bold text-2xl"><%= @book.publish_year %></span>
      </div>
    </div>
    <div class="p-4 border-t border-b text-lg text-gray-700">
      <span class="flex items-center mb-4">
        <i class="far fa-clock fa-fw mr-4 text-gray-900"></i> <%= @book.available? ? "Available" : "Not Available" %>
      </span>
      <% if !@book.available? %>
        <span class="flex items-center">
          <i class="far fa-user fa-fw mr-4 text-gray-900"></i> Borrowed by <%= @book.current_borrow.user.full_name %>
        </span>
        <span class="flex items-center">
          <i class="far fa-calendar fa-fw mr-4 text-gray-900"></i> Due Date: <%= @book.current_borrow.ended_at || "Not specified" %>
        </span>
      <% end %>
    </div>
    <% if @book.available? %>
      <div class="p-4 flex items-center text-lg text-gray-600">
        <%= form_with url: borrows_path, method: :post, local: true do %>
          <%= hidden_field_tag :book_id, @book.id %>
          <%= submit_tag 'Borrow', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-4 px-8 rounded ml-4" %>
        <% end %>
      </div>
    <% else %>
      <% if @book.current_borrow.user == current_user %>
        <div class="p-4 flex items-center text-lg text-gray-600">
          <%= button_to 'Return Book', borrow_path(@book.current_borrow), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-4 px-8 rounded ml-4" %>
        </div>
      <% else %>
        <div class="p-4 text-lg text-gray-600">
          <span>Currently unavailable</span>
        </div>
      <% end %>
    <% end %>
    <div class="p-4 flex justify-between items-center text-lg text-gray-600">
      <%= link_to 'Edit', edit_book_path(@book), class: "bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded" %>
      <%= button_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
    <div class="p-4 text-lg text-gray-600">
      <%= link_to 'Borrow History', history_book_path(@book), class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  </div>
</div>

app/views/borrows/_borrow.html.erb
<div id="<%= dom_id borrow %>">
  <p>
    <strong>User:</strong>
    <%= borrow.user_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= borrow.book_id %>
  </p>

  <p>
    <strong>Started at:</strong>
    <%= borrow.started_at %>
  </p>

  <p>
    <strong>Ended at:</strong>
    <%= borrow.ended_at %>
  </p>

</div>

app/views/borrows/_form.html.erb
<%= form_with(model: borrow) do |form| %>
  <% if borrow.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(borrow.errors.count, "error") %> prohibited this borrow from being saved:</h2>

      <ul>
        <% borrow.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :started_at, style: "display: block" %>
    <%= form.datetime_field :started_at %>
  </div>

  <div>
    <%= form.label :ended_at, style: "display: block" %>
    <%= form.datetime_field :ended_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/borrows/edit.html.erb
<h1>Editing borrow</h1>

<%= render "form", borrow: @borrow %>

<br>

<div>
  <%= link_to "Show this borrow", @borrow %> |
  <%= link_to "Back to borrows", borrows_path %>
</div>

app/views/borrows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Borrows</h1>

<div id="borrows">
  <% @borrows.each do |borrow| %>
    <%= render borrow %>
    <p>
      <%= link_to "Show this borrow", borrow %>
    </p>
  <% end %>
</div>

<%= link_to "New borrow", new_borrow_path %>

app/views/borrows/new.html.erb
<h1>New borrow</h1>

<%= render "form", borrow: @borrow %>

<br>

<div>
  <%= link_to "Back to borrows", borrows_path %>
</div>

app/views/borrows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @borrow %>

<div>
  <%= link_to "Edit this borrow", edit_borrow_path(@borrow) %> |
  <%= link_to "Back to borrows", borrows_path %>

  <%= button_to "Destroy this borrow", @borrow, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  <!-- Ajouter le lien CDN de Tailwind CSS ici -->
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="bg-gray-100 text-gray-800">
<nav class="bg-gray-800 p-4 text-white sticky top-0 z-10">
  <div class="container mx-auto flex justify-between items-center">
    <div class="flex items-center space-x-4">
      <%= link_to 'LibraryApp', root_path, class: "text-2xl font-bold" %>
      <%= link_to 'Books', books_path, class: "hover:underline" %>
      <% if logged_in? %>
        <%= link_to 'My Borrows', dashboard_path, class: "hover:underline" %>
        <%= link_to 'Profile', user_path(current_user), class: "hover:underline" %>
      <% end %>
    </div>
    <div class="flex items-center space-x-4">
      <% if logged_in? %>
        <span class="mr-2">Logged in as <%= current_user.email %></span>
        <%= button_to 'Logout', logout_path, method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
      <% else %>
        <%= link_to 'Login', login_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
        <%= link_to 'Register', register_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
      <% end %>
    </div>
  </div>
</nav>

<div class="container mx-auto mt-10">
  <% flash.each do |key, value| %>
    <div class="<%= key == 'notice' ? 'bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4' : 'bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4' %>" role="alert">
      <strong class="font-bold"><%= key.capitalize %></strong>
      <span class="block sm:inline"><%= value %></span>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/users/_user.html.erb
<div class="p-4 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
  <span class="font-medium">User Information:</span>
  <ul>
    <li>Name: <%= user.name %></li>
    <li>Email: <%= user.email %></li>
  </ul>
</div>

app/views/users/dashboard.html.erb
<h1 class="text-3xl font-bold mb-4">My Borrowed Books</h1>

<div class="mb-4">
  <%= link_to 'All', dashboard_path, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mr-2" %>
  <%= link_to 'Not Returned', dashboard_path(filter: 'not_returned'), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-2" %>
  <%= link_to 'Returned', dashboard_path(filter: 'returned'), class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
</div>

<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
  <% @borrows.each do |borrow| %>
    <%= render partial: 'books/book_card', locals: { book: borrow.book } %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-3xl font-bold mb-4">Edit Profile</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back to Profile', user_path(@user), class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<section class="gradient-form h-full bg-neutral-200 dark:bg-neutral-700">
  <div class="container h-full p-10">
    <div class="flex h-full flex-wrap items-center justify-center text-neutral-800 dark:text-neutral-200">
      <div class="w-full max-w-3xl">
        <div class="block rounded-lg bg-white shadow-lg dark:bg-neutral-800">
          <div class="g-0 lg:flex lg:flex-wrap">
            <!-- Left column container-->
            <div class="px-4 md:px-0 lg:w-full">
              <div class="md:mx-6 md:p-12">
                <!--User Profile-->
                <div class="text-center">
                  <img
                    class="mx-auto w-24 h-24 rounded-full"
                    src="https://tecdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                    alt="profile picture" />
                  <h4 class="mb-4 mt-1 pb-1 text-2xl font-semibold">
                    <%= @user.first_name %> <%= @user.last_name %>
                  </h4>
                </div>

                <div class="mb-4">
                  <p><strong>Email:</strong> <%= @user.email %></p>
                  <p><strong>Phone:</strong> <%= @user.phone %></p>
                  <p><strong>Address:</strong> <%= @user.address %></p>
                  <p><strong>Date of Birth:</strong> <%= @user.date_of_birth %></p>
                  <p><strong>Membership Type:</strong> <%= @user.membership_type %></p>
                  <p><strong>Membership Expiry Date:</strong> <%= @user.membership_expiry_date %></p>
                </div>

                <div class="flex justify-between">
                  <%= link_to 'Edit Profile', edit_user_path(@user), class: "bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded" %>
                  <%= button_to 'Delete Account', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
                </div>
              </div>
            </div>

            <!-- Right column container with background and description-->
            <div class="flex items-center rounded-b-lg lg:w-full lg:rounded-e-lg lg:rounded-bl-none" style="background: linear-gradient(to right, #ee7724, #d8363a, #dd3675, #b44593)">
              <div class="px-4 py-6 text-white md:mx-6 md:p-12">
                <h4 class="mb-6 text-xl font-semibold">
                  We are more than just a library
                </h4>
                <p class="text-sm">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>